files:
  - source: /Patch-pack-original/kubejs/assets/
    ignore:
      - /Patch-pack-original/kubejs/assets/kubejs/textures
      - /Patch-pack-original/kubejs/assets/alexsmobs
    translation: '%original_path%/zh_cn.json'
