#"files": [
#  {
#    "source": "/locale/en/folder1/[0-2].txt",                                       #source files filter
#    "translation": "/locale/%two_letters_code%/folder1/%original_file_name%"        #where translations are stored
#  },
#  {
#    "source": "/locale/en/folder2/[0-2].txt",
#    "translation": "/locale/%two_letters_code%/folder2/%original_file_name%"
#  }
#]

#........your project configuration........
#"files": [
#  {
#    "source": "/**/*.*",                             #upload all files that  the base_path contains
#    "translation": "/**/%two_letters_code%_%original_file_name%",
#    "ignore": [
#      "/**/%two_letters_code%_%original_file_name%", #ignore the translated files
#      "/**/?.txt",                                   #ignore 1.txt, a.txt, folder/1.txt, folder/a.txt
#      "/**/[0-9].txt",                               #ignore 1.txt, folder/1.txt
#      "/**/*\\?*.txt",                               #ignore crowdin?test.txt, folder/crowdin?test.txt
#      "/**/[0-9][0-9][0-9].txt",                     #ignore 123.txt , folder/123.txt
#      "/**/[0-9]*_*.txt"                             #ignore 123_test.txt, folder/123_test.txt
#    ]
#  }
#]

#........your project configuration........
#"files": [
#  {
#    "source": "/**/*.*",                             #upload all files that  the base_path contains
#    "translation": "/**/%two_letters_code%_%original_file_name%",
#    "ignore": [
#      "/**/%two_letters_code%_%original_file_name%", #ignore the translated files
#      "/**/?.txt",                                   #ignore 1.txt, a.txt, folder/1.txt, folder/a.txt
#      "/**/[0-9].txt",                               #ignore 1.txt, folder/1.txt
#      "/**/*\\?*.txt",                               #ignore crowdin?test.txt, folder/crowdin?test.txt
#      "/**/[0-9][0-9][0-9].txt",                     #ignore 123.txt , folder/123.txt
#      "/**/[0-9]*_*.txt"                             #ignore 123_test.txt, folder/123_test.txt
#    ]
#  }
#]
